version: '3'

services:
  website:
    image: nginx:latest
    container_name: dashboard
    ports:
      - "8080:80"
    volumes:
      - ./shared:/usr/share/nginx/html:ro
    restart: unless-stopped
